force-app/main/default/objects/Case/fields/FS_Area__c.field-meta.xml
<CustomField>
    <fullName>FS_Area__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N1. OMNIA</fullName>
            </value>
            <value>
                <fullName>N1. CORE</fullName>
            </value>
            <value>
                <fullName>N2-OMNIA</fullName>
            </value>
            <value>
                <fullName>N2- CORE</fullName>
            </value>
            <value>
                <fullName>QA CC-OMNIA</fullName>
            </value>
            <value>
                <fullName>QA CC-CORE</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
            <value>
                <fullName>PS</fullName>
            </value>
            <value>
                <fullName>N1. TESORERIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_FechaCompromisoEntrega__c.field-meta.xml
<CustomField>
    <fullName>FS_FechaCompromisoEntrega__c</fullName>
    <label>Fecha Compromiso Entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Issue_Type__c</fullName>
    <label>Issue Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>FS_Project_Id__c</fullName>
    <label>Project Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_RequiereInformacionAdicional__c.field-meta.xml
<CustomField>
    <fullName>FS_RequiereInformacionAdicional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Requiere información adicional?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubEstado__c.field-meta.xml
<CustomField>
    <fullName>FS_SubEstado__c</fullName>
    <label>Sub Estados</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apertura de caso</fullName>
                <default>true</default>
                <label>Apertura de caso</label>
            </value>
            <value>
                <fullName>Entrega 1a respuesta</fullName>
            </value>
            <value>
                <fullName>Análisis N1</fullName>
            </value>
            <value>
                <fullName>Aprobación Consulta N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solicitud N2</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Definitivo</fullName>
            </value>
            <value>
                <fullName>Desarrollo Incidente Puntual</fullName>
            </value>
            <value>
                <fullName>Revisión Documentación N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución IP-N2</fullName>
            </value>
            <value>
                <fullName>Aprobación de Solución IP-Release</fullName>
            </value>
            <value>
                <fullName>Costo Aceptado</fullName>
            </value>
            <value>
                <fullName>Costo Rechazado</fullName>
            </value>
            <value>
                <fullName>Análisis Falla Operativa</fullName>
            </value>
            <value>
                <fullName>Escalado a N2</fullName>
            </value>
            <value>
                <fullName>Análisis N2</fullName>
            </value>
            <value>
                <fullName>Envío de respuesta</fullName>
            </value>
            <value>
                <fullName>Respuesta aceptada</fullName>
            </value>
            <value>
                <fullName>Respuesta rechazada</fullName>
            </value>
            <value>
                <fullName>En reproceso por rechazo</fullName>
            </value>
            <value>
                <fullName>Pendiente Respuesta Cliente</fullName>
            </value>
            <value>
                <fullName>En Espera de Respuesta del Cliente</fullName>
            </value>
            <value>
                <fullName>Elaboración Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Aprobación Diseño Técnico</fullName>
            </value>
            <value>
                <fullName>Validación-Entrega de Fuentes</fullName>
            </value>
            <value>
                <fullName>Elaboración Solución Definitiva</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva N2</fullName>
            </value>
            <value>
                <fullName>Aprobación Solución Definitiva Releases</fullName>
            </value>
            <value>
                <fullName>Escalado a QA</fullName>
            </value>
            <value>
                <fullName>Elaboración Plan de Pruebas</fullName>
            </value>
            <value>
                <fullName>Aprobación Plan de Pruebas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FS_Requerimiento.recordType-meta.xml
<RecordType>
    <fullName>FS_Requerimiento</fullName>
    <active>true</active>
    <businessProcess>FS_Requerimiento</businessProcess>
    <label>Requerimiento</label>
</RecordType>

force-app/main/default/objects/FS_Project_Jira__mdt/FS_Project_Jira__mdt.object-meta.xml
<CustomObject>
    <label>Project Jira</label>
    <pluralLabel>Projects Jira</pluralLabel>
</CustomObject>

force-app/main/default/objects/FS_Project_Jira__mdt/fields/FS_Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Issue_Type__c</fullName>
    <label>Issue Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Project_Jira__mdt/fields/FS_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>FS_Project_Id__c</fullName>
    <label>Project Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Project_Jira__mdt/fields/FS_Sub_Tipo__c.field-meta.xml
<CustomField>
    <fullName>FS_Sub_Tipo__c</fullName>
    <label>Sub Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puntual</fullName>
            </value>
            <value>
                <fullName>Definitivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Project_Jira__mdt/fields/FS_Tipo_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>FS_Tipo_de_Registro__c</fullName>
    <label>Tipo de Registro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consulta</fullName>
                <default>true</default>
                <label>Consulta</label>
            </value>
            <value>
                <fullName>Incidente</fullName>
            </value>
            <value>
                <fullName>Requerimiento</fullName>
            </value>
            <value>
                <fullName>Solicitud (Falla Operativa)</fullName>
            </value>
            <value>
                <fullName>Control de Cambios</fullName>
            </value>
            <value>
                <fullName>Tiempo y Materiales - Con Sprints</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeCaseRecordType.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<info@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             ChangeCaseRecordType
* @description      Class to validate the record type change.
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2024-11-25   Intellect Systems             Initial version.
**************************************************************************************************************
*/

public with sharing class ChangeCaseRecordType {

    public static final String REQUERIMIENTO_TIPO_REGISTRO = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FS_Requerimiento').getRecordTypeId();

    /**
     * @method      validateChangeRecordType
     * @description Method to assign new case owner if recordtype in changed
     * @author      Intellect Systems - 2024-11-25
     * @param       records
     * @param       oldRecords
     */
    public static void validateChangeRecordType(List<Case> records, Map<Id, Case> oldRecords) {
        // Get a list of records
        List<FS_Project_Jira__mdt> metadataRecords = [  SELECT  Id, FS_Tipo_de_Registro__c, FS_Sub_Tipo__c, FS_Project_Id__c, FS_Issue_Type__c
                                                        FROM    FS_Project_Jira__mdt 
                                                        WITH    SECURITY_ENFORCED  ];

        //Close Jira
        if(!records.isEmpty()) {
            CreateJiraRecord.checkCloseJira(records, oldRecords);
        }

        User usuario = [    SELECT  Contact.Account.FS_Carterizacion__c, Contact.Account.FS_ServicioRemoto__c, Contact.Account.FS_ColaAtencion__c, Contact.Account.FS_CorreosNotificacionesServicios__c, Contact.Account.FS_Correos_Notificaciones_PS__c  
                            FROM    user  
                            WHERE   Id =: userInfo.getUserId()    ];

        for(Case caso : records) { 
            Boolean esCore = CaseTriggerHelper.ProductoCore(caso);
            if(REQUERIMIENTO_TIPO_REGISTRO != caso.RecordTypeId) {
                caso.FS_Area__c = esCore ? 'N1. CORE' : 'N1. OMNIA';
            } else {
                caso.FS_Area__c = 'PS';
            }

            caso.Status = 'Nuevo';
            caso.FS_TipoIncidente__c = '';
            caso.FS_SubEstado__c = '';
            caso.FS_FechaCompromisoEntrega__c = null;
            caso.FS_RequiereInformacionAdicional__c = false;
            caso.FS_NumeroRequerimientosNuevo__c = null;

            if(REQUERIMIENTO_TIPO_REGISTRO != caso.RecordTypeId) {
                if(usuario.Contact.Account.FS_ServicioRemoto__c){
                    caso.OwnerId = [Select Id from Group Where DeveloperName = :usuario.Contact.Account.FS_ColaAtencion__c and Type = 'Queue'].Id;
                }else{
                    caso.OwnerId = [Select Id from Group Where DeveloperName = :(esCore ? CaseTriggerHelper.COLA_ATENCION_N1_CORE : CaseTriggerHelper.COLA_ATENCION_N1_OMNIA) and Type = 'Queue'].Id;
                }
            } else {                
                map<String, FS_Gestor_Cuenta__c> mapRecords = new map<String, FS_Gestor_Cuenta__c>([	SELECT 	Id, FS_Project_Manager__c  
                                                                                                        FROM 	FS_Gestor_Cuenta__c
                                                                                                        WHERE 	FS_Cuenta__c =: caso.AccountId and FS_Principal__c =: true	 ]);
                if(REQUERIMIENTO_TIPO_REGISTRO == caso.RecordTypeId && mapRecords.size() > 0) {	
                    for(Id key : mapRecords.keySet()) {
                        caso.OwnerId = mapRecords.get(key).FS_Project_Manager__c;    
                    }
                }
            }
        }
    }
}