force-app/main/default/objects/Case/fields/FS_esTesoreria__c.field-meta.xml
<CustomField>
    <fullName>FS_esTesoreria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>esTesoreria</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Núcleo del Sistema</fullName>
            </value>
            <value>
                <fullName>Cajas y Bóveda (Módulo 3)</fullName>
            </value>
            <value>
                <fullName>Captaciones a la Vista (Módulo 4)</fullName>
            </value>
            <value>
                <fullName>Captaciones a Plazo (Módulo 5)</fullName>
            </value>
            <value>
                <fullName>Colocaciones (Módulo 6)</fullName>
            </value>
            <value>
                <fullName>Comercio Exterior (Módulo 10)</fullName>
            </value>
            <value>
                <fullName>Tesorería (Módulo 12)</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito (Módulo 15)</fullName>
            </value>
            <value>
                <fullName>DIPS (Modulo 19)</fullName>
            </value>
            <value>
                <fullName>Contabilidad (Módulo 20)</fullName>
            </value>
            <value>
                <fullName>Reportes (Módulo 21)</fullName>
            </value>
            <value>
                <fullName>Garantías (Módulo 28)</fullName>
            </value>
            <value>
                <fullName>Calendarizador Procesos Bach</fullName>
            </value>
            <value>
                <fullName>Core Tarjeta de Crédito</fullName>
            </value>
            <value>
                <fullName>MCM (MultiChannel Managemt)</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>BRE (Motor de reglas)</fullName>
            </value>
            <value>
                <fullName>Business Application Products (Plataforma de Ventas)</fullName>
            </value>
            <value>
                <fullName>BackOffice</fullName>
            </value>
            <value>
                <fullName>Online Banking Personas</fullName>
            </value>
            <value>
                <fullName>Mobile Banking Personas</fullName>
            </value>
            <value>
                <fullName>Kioskos</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Rapid Cash</fullName>
            </value>
            <value>
                <fullName>DIPS</fullName>
            </value>
            <value>
                <fullName>ECCO</fullName>
            </value>
            <value>
                <fullName>IMS</fullName>
            </value>
            <value>
                <fullName>Flujos</fullName>
            </value>
            <value>
                <fullName>CLIENTES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
            <value>
                <fullName>FORWARDS</fullName>
            </value>
            <value>
                <fullName>FUTUROS</fullName>
            </value>
            <value>
                <fullName>GARANTIAS</fullName>
            </value>
            <value>
                <fullName>GENERAL</fullName>
            </value>
            <value>
                <fullName>INTERBANCARIOS</fullName>
            </value>
            <value>
                <fullName>OBLIGACIONES</fullName>
            </value>
            <value>
                <fullName>OPCIONES</fullName>
            </value>
            <value>
                <fullName>PASIVOS A PLAZOS</fullName>
            </value>
            <value>
                <fullName>RENTA VARIABLE</fullName>
            </value>
            <value>
                <fullName>REPOS</fullName>
            </value>
            <value>
                <fullName>SPOT</fullName>
            </value>
            <value>
                <fullName>SWAPS</fullName>
            </value>
            <value>
                <fullName>TITULOS VALORES</fullName>
            </value>
            <value>
                <fullName>Tesoreria</fullName>
                <isActive>false</isActive>
                <label>Tesoreria</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SubModuloCatalogo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModuloCatalogo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Modulo Catalogo</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No existe un sub Modulo para la combinación de producto y Modulo seleccionado en el Filtro.</errorMessage>
        <filterItems>
            <field>$Source.FS_Producto__c</field>
            <operation>equals</operation>
            <valueField>FS_ProductCatalog__c.FS_Producto__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.FS_Modulo__c</field>
            <operation>equals</operation>
            <valueField>FS_ProductCatalog__c.FS_Modulo__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_ProductCatalog__c.FS_Active__c</field>
            <operation>equals</operation>
            <value>true</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_ProductCatalog__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FS_Requerimiento.recordType-meta.xml
<RecordType>
    <fullName>FS_Requerimiento</fullName>
    <active>true</active>
    <businessProcess>FS_Requerimiento</businessProcess>
    <label>Requerimiento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/FS_TiempoMateriales.recordType-meta.xml
<RecordType>
    <fullName>FS_TiempoMateriales</fullName>
    <active>true</active>
    <businessProcess>FS_TiempoMateriales</businessProcess>
    <description>Tipo de registro para casos de tiempo y materiales</description>
    <label>Tiempo y Materiales</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/FS_TiempoMaterialesSprints.recordType-meta.xml
<RecordType>
    <fullName>FS_TiempoMaterialesSprints</fullName>
    <active>true</active>
    <businessProcess>FS_TiempoMaterialesSprints</businessProcess>
    <label>Tiempo y Materiales - Con Sprints</label>
</RecordType>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Modulo__c.field-meta.xml
<CustomField>
    <fullName>FS_Modulo__c</fullName>
    <label>Módulo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_Producto__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BackOffice</fullName>
            </value>
            <value>
                <fullName>BRE (Motor de reglas)</fullName>
            </value>
            <value>
                <fullName>Business Application Generator</fullName>
            </value>
            <value>
                <fullName>Business Application Products (Plataforma de Ventas)</fullName>
            </value>
            <value>
                <fullName>Business Support Aplication</fullName>
            </value>
            <value>
                <fullName>Cajas y Bóveda (Módulo 3)</fullName>
            </value>
            <value>
                <fullName>Calendarizador Procesos Bach</fullName>
            </value>
            <value>
                <fullName>Captaciones a la Vista (Módulo 4)</fullName>
            </value>
            <value>
                <fullName>Captaciones a Plazo (Módulo 5)</fullName>
            </value>
            <value>
                <fullName>Colocaciones (Módulo 6)</fullName>
            </value>
            <value>
                <fullName>Comercio Exterior (Módulo 10)</fullName>
            </value>
            <value>
                <fullName>Contabilidad (Módulo 20)</fullName>
            </value>
            <value>
                <fullName>Core Tarjeta de Crédito</fullName>
            </value>
            <value>
                <fullName>DIPS</fullName>
            </value>
            <value>
                <fullName>DIPS (Modulo 19)</fullName>
            </value>
            <value>
                <fullName>ECCO</fullName>
            </value>
            <value>
                <fullName>Enterprise Banking</fullName>
            </value>
            <value>
                <fullName>Flujos</fullName>
            </value>
            <value>
                <fullName>Garantías (Módulo 28)</fullName>
            </value>
            <value>
                <fullName>IMS</fullName>
            </value>
            <value>
                <fullName>Kioskos</fullName>
            </value>
            <value>
                <fullName>MCM (MultiChannel Managemt)</fullName>
            </value>
            <value>
                <fullName>Mobile Banking Personas</fullName>
            </value>
            <value>
                <fullName>Núcleo del Sistema</fullName>
            </value>
            <value>
                <fullName>Online Banking Personas</fullName>
            </value>
            <value>
                <fullName>Rapid Cash</fullName>
            </value>
            <value>
                <fullName>Reportes (Módulo 21)</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito (Módulo 15)</fullName>
            </value>
            <value>
                <fullName>Tesorería (Módulo 12)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_Producto__c.field-meta.xml
<CustomField>
    <fullName>FS_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FISA System</fullName>
            </value>
            <value>
                <fullName>FISA CreditCard</fullName>
            </value>
            <value>
                <fullName>OMNIA</fullName>
            </value>
            <value>
                <fullName>FISA FISS</fullName>
            </value>
            <value>
                <fullName>FORWARDS</fullName>
            </value>
            <value>
                <fullName>FUTUROS</fullName>
            </value>
            <value>
                <fullName>GARANTIAS</fullName>
            </value>
            <value>
                <fullName>GENERAL</fullName>
            </value>
            <value>
                <fullName>INTERBANCARIOS</fullName>
            </value>
            <value>
                <fullName>OBLIGACIONES</fullName>
            </value>
            <value>
                <fullName>OPCIONES</fullName>
            </value>
            <value>
                <fullName>PASIVOS A PLAZOS</fullName>
            </value>
            <value>
                <fullName>RENTA VARIABLE</fullName>
            </value>
            <value>
                <fullName>REPOS</fullName>
            </value>
            <value>
                <fullName>SPOT</fullName>
            </value>
            <value>
                <fullName>SWAPS</fullName>
            </value>
            <value>
                <fullName>TITULOS VALORES</fullName>
            </value>
            <value>
                <fullName>Tesoreria</fullName>
                <isActive>false</isActive>
                <label>Tesoreria</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_ProductoTesoreria__c.field-meta.xml
<CustomField>
    <fullName>FS_ProductoTesoreria__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo de Checkbox que nos permite determinar si el producto corresponde o no al flujo de tesorería.</description>
    <label>Producto Tesorería</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_ProductoAdquirido__c/fields/FS_SubModuloCatalogo__c.field-meta.xml
<CustomField>
    <fullName>FS_SubModuloCatalogo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Módulo Catálogo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FS_ProductCatalog__c.FS_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.FS_Producto__c</field>
            <operation>equals</operation>
            <valueField>FS_ProductCatalog__c.FS_Producto__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.FS_Modulo__c</field>
            <operation>equals</operation>
            <valueField>FS_ProductCatalog__c.FS_Modulo__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_ProductCatalog__c</referenceTo>
    <relationshipLabel>Productos Adquiridos</relationshipLabel>
    <relationshipName>Productos_Adquiridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**
**************************************************************************************************************
* @author           Intellect Systems href=<infor@intellectsystems.net>
* @project          Fisa Ecuador - Implementación CRM
* @name             CaseTriggerHandler
* @description      Handler class to case Trigger called: CaseTrigger
* @changes
* ----------   ---------------------------   -----------------------------------------------------------------
* Date         Author                        Description
* ----------   ---------------------------   -----------------------------------------------------------------
* 2023-07-14   Intellect Systems             Initial version.
* 2024-24-03   Intellect Systems             Method removed: validationChatter, after reviewing that they are unnecessary.
**************************************************************************************************************
*/

public without sharing class CaseTriggerHandler {

    public static final String REQUERIMIENTO_TIPO_REGISTRO = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FS_Requerimiento').getRecordTypeId();
    public static final String CONTROLDECAMBIO_TIPO_REGISTRO = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FS_ControlCambios').getRecordTypeId();
    public static final String TIEMPOMATERIALES_TIPO_REGISTRO = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FS_TiempoMateriales').getRecordTypeId();
    public static final String TIEMPOMATERIALSPRINTS_TIPO_REGISTRO = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('FS_TiempoMaterialesSprints').getRecordTypeId();


    public static void beforeInsert(List<Case> newCaseList){
        System.debug('CPU Time (ms): ' + Limits.getCpuTime() + ' / ' + Limits.getLimitCpuTime());
        System.debug('Heap Size (bytes): ' + Limits.getHeapSize() + ' / ' + Limits.getLimitHeapSize());
        CaseTriggerHelperPMPS.assignCases(newCaseList);
    }
    
    public static void afterInsert(List<Case> newCaseList, Map<Id, Case> oldCaseMap){
        CaseTriggerHelper.historialDescripcion(newCaseList);
        CaseTriggerHelper.historialCaso(newCaseList);
        
        List<Case> lstCaseTiempoMateriales = new List<Case>();
        Map<Id, Case> mpCaseCaseTiempoMateriales = new Map<Id, Case>();
        
        for(Case record : newCaseList) {
            if(record.RecordTypeId == TIEMPOMATERIALES_TIPO_REGISTRO || record.RecordTypeId == TIEMPOMATERIALSPRINTS_TIPO_REGISTRO){
                lstCaseTiempoMateriales.add(record);
            }
        }
        
        if(!lstCaseTiempoMateriales.isEmpty()){
            CaseTriggerHelperTM.sendToJiraTM(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
        }
        
    }
    
    public static void beforeUpdate(List<Case> newCaseList, Map<Id, Case> oldCaseMap) {
        List<Case> lstCaseRequerimiento = new List<Case>();
        Map<Id, Case> mpCaseRequerimiento = new Map<Id, Case>();
        
        List<Case> lstCaseTiempoMateriales = new List<Case>();
        Map<Id, Case> mpCaseCaseTiempoMateriales = new Map<Id, Case>();

        List<Case> lstCaseRecordCare = new List<Case>();
        Map<Id, Case> mpCaseRecordCare = new Map<Id, Case>();
        
        List<Case> lstCaseRecordTesoreria = new List<Case>();
        Map<Id, Case> mpCaseRecordTesoreria = new Map<Id, Case>();
        
        Set<String> ProductoCase = new Set<String>();
        Set<String> ModuloCase = new Set<String>();
        Set<String> SubModuloCase = new Set<String>();
        Set<String> accCase = new Set<String>();
        /*for(Case record : newCaseList) {
            ProductoCase.add(record.FS_Producto__c);
            ModuloCase.add(record.FS_Modulo__c);
            SubModuloCase.add(record.FS_SubModuloCatalogo__c);
            accCase.add(record.AccountId);
        }
        
        List<FS_ProductoAdquirido__c> ltsProductosAdq = [     SELECT  FS_Cuenta__c, FS_Producto__c, FS_Modulo__c, FS_SubModuloCatalogo__c, FS_Esta_activo__c 
                                                            FROM    FS_ProductoAdquirido__c 
                                                            WHERE   FS_Cuenta__c IN: accCase AND FS_Producto__c IN: ProductoCase AND FS_Modulo__c IN: ModuloCase
                                                            AND     FS_SubModuloCatalogo__c IN: SubModuloCase  AND FS_ProductoTesoreria__c = true];
        
        Map<String, FS_ProductoAdquirido__c> productoMap = new Map<String, FS_ProductoAdquirido__c>();
        for (FS_ProductoAdquirido__c pa : ltsProductosAdq) {
            //
            String key = pa.FS_Cuenta__c + '-' + pa.FS_Producto__c + '-' + pa.FS_Modulo__c;// + '-' + pa.FS_SubModuloCatalogo__c;
            productoMap.put(key, pa);
        }*/

        for(Case record : newCaseList) {
            Case caso = oldCaseMap.get(record.Id);
            String key = record.AccountId + '-' + record.FS_Producto__c + '-' + record.FS_Modulo__c; //+ '-' + record.FS_SubModuloCatalogo__c;
            if(record.RecordTypeId == REQUERIMIENTO_TIPO_REGISTRO || record.RecordTypeId == CONTROLDECAMBIO_TIPO_REGISTRO) {
                lstCaseRequerimiento.add(record);
                mpCaseRequerimiento.put(caso.Id, caso);
            } else if(record.RecordTypeId == TIEMPOMATERIALES_TIPO_REGISTRO || record.RecordTypeId == TIEMPOMATERIALSPRINTS_TIPO_REGISTRO){
                lstCaseTiempoMateriales.add(record);
                mpCaseCaseTiempoMateriales.put(caso.Id, caso);
            } else if(record.FS_esTesoreria__c == true) {
                lstCaseRecordTesoreria.add(record);
                mpCaseRecordTesoreria.put(caso.Id, caso);
            } else {
                lstCaseRecordCare.add(record);
                mpCaseRecordCare.put(caso.Id, caso);
            }
            
        }

        CaseTriggerHelper.validacionEstado(newCaseList, oldCaseMap);
        CaseTriggerHelper.validacionProducto(newCaseList, oldCaseMap);
        CaseTriggerHelper.esCliente(newCaseList);

        if(!lstCaseRecordCare.isEmpty()) {
            CaseTriggerHelper.validacionAgenteN2(lstCaseRecordCare);
            CaseTriggerHelper.validacionSubEstado(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionCamposAprobacion(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.informacionCompleta(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionTipo(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.aceptaRespuesta(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.actualizacionDescripcion(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.horasSolicitud(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionSolucion(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.acepta1erCosto(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionFechaEntrega(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionTipoIncidente(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLResultadoAnalasis(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAutorizacionSolucionIPN2(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionSolucionIPRelease(lstCaseRecordCare, mpCaseRecordCare);        
            CaseTriggerHelper.validacionSolucionCortoPlazo(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLDisenioTecnico(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionDisenioTecnico(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLCodigoFuente(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLSolucionDefinitiva(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionSolucionDefinitivaN2(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionSolucionDefinitivaRelease(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLPlanPruebas(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionPlanPruebas(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLAmbientePruebas(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionInstalacionRelease(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionURLEvidenciaPruebas(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAprobacionCertificacionQA(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionUrlEntregaParche(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAceptaInstalacionParche(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionAceptaPaseProduccion(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.validacionIngProducto(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.asignarAprobadorActual(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.mapeoFechaEstado(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.assignDeliveryDate(lstCaseRecordCare, mpCaseRecordCare);
            CaseTriggerHelper.upsertCaseJira(lstCaseRecordCare, mpCaseRecordCare);
        }
        
        if(!lstCaseRequerimiento.isEmpty()) {
            CaseTriggerHelperPMPS.preventChangeCaseValues(lstCaseRecordCare, mpCaseRequerimiento);
            CaseTriggerHelperPMPS.sendToJiraPMPS(lstCaseRequerimiento, mpCaseRequerimiento);
            CaseTriggerHelperPMPS.sendNotification(lstCaseRequerimiento, mpCaseRequerimiento);
            CaseTriggerHelperPMPS.actualizacionDescripcion(lstCaseRequerimiento, mpCaseRequerimiento);
            CaseTriggerHelperPMPS.informacionCompleta(lstCaseRequerimiento, mpCaseRequerimiento);
            CaseTriggerHelper.validacionProducto(lstCaseRequerimiento, mpCaseRequerimiento);
            CaseTriggerHelperPMPS.envioNotificacionFinanzas(lstCaseRequerimiento, mpCaseRequerimiento);
            if(UserInfo.getUserType() != 'Guest'){
                CaseTriggerHelperPMPS.aceptaRespuesta(lstCaseRequerimiento, mpCaseRequerimiento);
                CaseTriggerHelperPMPS.envioNotificacionComunidad(lstCaseRequerimiento, mpCaseRequerimiento);
            }
        }
        
        
        if(!lstCaseTiempoMateriales.isEmpty()){
            CaseTriggerHelperTM.preventChangeCaseValues(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.sendToJiraPMPS(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.sendNotification(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.actualizacionDescripcion(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.informacionCompleta(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelper.validacionProducto(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            //CaseTriggerHelperTM.envioNotificacionFinanzas(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.validateChildrenCases(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.UpdateTotalDays(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            if(UserInfo.getUserType() != 'Guest'){
                CaseTriggerHelperTM.aceptaRespuesta(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
                CaseTriggerHelperTM.envioNotificacionComunidad(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            }
        }
        
        //Tesoreria Flow
        if(!lstCaseRecordTesoreria.isEmpty()){
            CaseTriggerHelperTS.changeStatus(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
            CaseTriggerHelperTS.aceptaRespuesta(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
            CaseTriggerHelperTS.sendToJiraTS(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
            CaseTriggerHelperTS.actualizacionDescripcion(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
            CaseTriggerHelperTS.mapeoFechaEstado(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
            //CaseTriggerHelperTS.updateJiraRecordTS(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
        }
        

        List<Case> lstCase = new List<Case>();
        Map<Id, Case> mpCase = new Map<Id, Case>();
        for(Case record : newCaseList) {
            Case caso = oldCaseMap.get(record.Id); 
            if(record.RecordTypeId != caso.RecordTypeId) {
                lstCase.add(record);
                mpCase.put(caso.Id, caso);
            }
        }

        if(!lstCase.isEmpty()) {
            ChangeCaseRecordType.validateChangeRecordType(lstCase, mpCase);
        }
        
        for(Case record : newCaseList) {
            Case caso = oldCaseMap.get(record.Id);
            if(record.Status != caso.Status && (record.Status == 'Cerrado' || record.Status == 'Dado de Baja')) {
                List<Id> caseIds = new List<Id>();
            	CaseIds.add(record.Id);
            	//MilestoneClose.completeMilestone(caseIds);
                
            }
            
        }
     
    }
    
    public static void afterUpdate(List<Case> newCaseList, Map<Id, Case> oldCaseMap) {
        Boolean executeFlag = true;

        List<Case> lstCaseRequerimiento = new List<Case>();
        Map<Id, Case> mpCaseRequerimiento = new Map<Id, Case>();

        List<Case> lstCaseRecordCare = new List<Case>();
        Map<Id, Case> mpCaseRecordCare = new Map<Id, Case>();
        
        List<Case> lstCaseTiempoMateriales = new List<Case>();
        Map<Id, Case> mpCaseCaseTiempoMateriales = new Map<Id, Case>();
        
        List<Case> lstCaseRecordTesoreria = new List<Case>();
        Map<Id, Case> mpCaseRecordTesoreria = new Map<Id, Case>();

        for(Case record : newCaseList) {
            Case caso = oldCaseMap.get(record.Id);
            if(record.RecordTypeId == REQUERIMIENTO_TIPO_REGISTRO || record.RecordTypeId == CONTROLDECAMBIO_TIPO_REGISTRO) {
                lstCaseRequerimiento.add(record);
                mpCaseRequerimiento.put(caso.Id, caso);
            } else if(record.RecordTypeId == TIEMPOMATERIALES_TIPO_REGISTRO || record.RecordTypeId == TIEMPOMATERIALSPRINTS_TIPO_REGISTRO){
                lstCaseTiempoMateriales.add(record);
                mpCaseCaseTiempoMateriales.put(caso.Id, caso);
            } else if(record.FS_esTesoreria__c == true){
                lstCaseRecordTesoreria.add(record);
                mpCaseRecordTesoreria.put(caso.Id, caso);
            } else {
                lstCaseRecordCare.add(record);
                mpCaseRecordCare.put(caso.Id, caso);
            }
        }

        CaseTriggerHelper.historialCaso(newCaseList, oldCaseMap);
        CaseTriggerHelper.UpdateFields(newCaseList, oldCaseMap);

        if(!lstCaseRecordCare.isEmpty()) {
            CaseTriggerHelper.solventarPregunta(lstCaseRecordCare, mpCaseRecordCare);
        }

        if(!lstCaseRequerimiento.isEmpty()) {
            CaseTriggerHelperPMPS.updateJiraRecordPMPS(lstCaseRequerimiento, mpCaseRequerimiento);
        }
        
        if(!lstCaseRecordTesoreria.isEmpty()) {
            CaseTriggerHelperTS.updateJiraRecordTS(lstCaseRecordTesoreria, mpCaseRecordTesoreria);
        }
        
        if(!lstCaseTiempoMateriales.isEmpty()) {
            CaseTriggerHelperTM.updateJiraRecordPMPS(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
            CaseTriggerHelperTM.changeStatus(lstCaseTiempoMateriales, mpCaseCaseTiempoMateriales);
        }
    }
    
    public static void afterDelete(List<Case> newCaseList) {
        CaseTriggerHelperPMPS.preventDeleteRecords(newCaseList);      
    }
    
}